---
- name: Install misc packages
  dnf:
    state: latest
    name:
      - bind-utils
      - curl
      - git
      - hping3
      - jq
      - lsof
      - nc
      - nftables
      - nmap
      - tcpdump
      - tmux
      - vim

- name: Install hvac
  pip:
    name: hvac
    state: present
    #extra_args: --user
